language: node_js
node_js:
  - "12"
deploy:
  provider: heroku
  api_key:
    secure: uAVnb3HLAdG5j3y/GSbUaGdIGNRAi1yiVHOaKZWOtaIZHN3vb/Q2eXXxVG1jdjbRzU6K/YM5EKmWN5JFdaHC3m8nhzXT8a7NjDcITsIJCSWbKq0eqphQdn7aLz/DDxYgtpNn+I0EfpakRhP4mFEoUJazuDxNCEowmN4Bl+NxmOIsNAGBpvDQQCQzO5tPVcGa726iORC8b+jiitx6I9T99P5XIgU8amP1tQpekEDtECKrEwa7foyZFsQw77WnroglE2YZ9pMMFYga2uU0IG9d6F0huMtObsRTvR8V3NEukQ6p3mL+JLFYmtAghFsDOCgLrAOoMM6ezKRwB5MBScuZEVCN2zIpZtWzc7GUcBzoKlOVuHeEgEqbQw0+/UNW9I4sParAVBJohVDKKJmONW3wSAorfgXopZw31rJOc+q0BcerqhyRUJC93oiRMUqcPL1QZSfJJ7sLXSD4RLpq6ERbKzbOiKPaWnxPowUPxnn0l5fHkmSc6hz21EcRDgqmk3NNFtaDRsG7Ndc6ff1TGRYaR4DpNPJGZmtnzO/RoS5yk7j7TZ5FimFF3s6byhyEJK00UjUYXZWiKoyQc5ZFh7LiiLhtFoOE3OpBgHT5UVteCWLQZuTDkdq3Mn25dLeyVaF4tn+02XK9hbOWXTBt1wLgSqUSOsp+fdmQThv+swzo6sM=
  app: helping-hand-drp08
